apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: swr.ap-southeast-1.myhuaweicloud.com/<namespace>/backend:latest
          ports:
            - containerPort: 3000
