apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: bXlzcWw=   # Base64 encoded (echo -n "mysql" | base64)
  password: cGFzc3dvcmQ=  # Base64 encoded (echo -n "password" | base64)
